### ISSUE TITLE
Version 1.2.1 broke highlighting

### ISSUE THREAD

**Issue by svew** [bpruitt-goddard/vscode-mermaid-syntax-highlight#51] opened 2021-05-11 22:54 UTC
Just installed plugin today, neither embedded mermaid in markdown nor .mmd files would highlight. Disabled all other markdown plugins, still didn't work. Reverted to version 1.2.0, plugin works!

**Comment by realvictorprm** [comment] 2021-05-12 10:28
same here

**Comment by bpruitt-goddard** [comment] 2021-05-12 20:21
Duplicate of #50

**Closed by bpruitt-goddard** 2021-05-12 20:21 UTC
